version = '1.0.0'

[git]
default-branch = 'main'
message-template = 'Bump version {{.Current}} -> {{.Next}}'
tag-template = 'v{{.Next}}'

[[file]]
path = 'README.md'
search = 'version="v{{.Current}}"'
